import type { Section } from "@/components/features/section-types";

export const BATTERY_TRADER_SECTIONS: Section[] = [
  { id: "bt-title", type: "heading", content: "Battery Trader" },
  { id: "bt-hero1", type: "image", src: "/images/battery-trader/hero-1.png", alt: "Battery Trader hero" },
  { id: "bt-meta", type: "meta", lines: [
    { label: "Client",   value: "PCI Energy Solutions" },
    { label: "Timeline", value: "Sept 2023–Mar 2024" },
    { label: "Platform", value: "SaaS" },
    { label: "Role",     value: "UX Research, Product Design" },
    { label: "Tools",    value: "Figma, Adobe CC, Microsoft Products" },
  ]},
  { id: "bt-intro-label", type: "subheading", content: "Introduction" },
  { id: "bt-intro", type: "paragraph", content: "Battery Trader is a web-based platform built for battery and renewable energy site owners to optimize operations, plan bids, and analyze trading performance across multiple energy markets. The software leverages real-time data, advanced analytics, and automation to empower users to make data-driven decisions and maximize profitability." },
  { id: "bt-hero2", type: "image", src: "/images/battery-trader/hero-2.png", alt: "Battery Trader platform overview", height: 183 },
  { id: "bt-goal-label", type: "subheading", content: "The Goal" },
  { id: "bt-goal", type: "paragraph", content: "Design a unified platform where energy traders and analysts can manage bids, monitor markets, and run strategy across multiple sites, without the complexity and fragmentation of existing tools." },
  { id: "bt-challenge-label", type: "subheading", content: "The Challenge" },
  { id: "bt-challenge", type: "paragraph", content: "Energy trading is complex, with users juggling multiple data sources, unpredictable market conditions, and manual processes for bidding and strategy creation. Many existing tools fail to provide a unified solution, resulting in inefficiencies, missed opportunities, and frustration." },
  { id: "bt-discovery-heading", type: "heading", content: "Discovery Phase" },
  { id: "bt-goals-split", type: "split", heading: "Define Project Goals",
    content: "Establish the primary objectives for Battery Trader, such as optimizing battery and renewable site operations, enhancing market bidding strategies, and providing comprehensive analytics.",
    src: "/images/battery-trader/business-flowchart.png", alt: "Battery Trader business flowchart", aspectRatio: "1392/932",
  },
  { id: "bt-structure-split", type: "split", heading: "Building the Structure",
    content: "Leveraging insights from the discovery phase, David spearheaded the creation of a streamlined sitemap for Battery Trader. Collaborating closely with project managers and engineers, the team refined the platform's structure to ensure intuitive navigation and alignment with user needs, balancing technical feasibility and optimal UX.",
    src: "/images/battery-trader/sitemap.png", alt: "Battery Trader sitemap", aspectRatio: "1392/898",
  },
  { id: "bt-requirements", type: "text-gallery", heading: "Identify User Requirements",
    content: "Engage with users, including site owners, energy market analysts, and regulatory bodies, to understand their expectations and requirements. Including discovery interviews with coordinating roles.",
    images: [
      { src: "/images/battery-trader/user-video-1.png",    alt: "User interview session 1", aspectRatio: "672/378"   },
      { src: "/images/battery-trader/user-video-2.png",    alt: "User interview session 2", aspectRatio: "672/378"   },
      { src: "/images/battery-trader/user-flowchart.png",  alt: "User research flowchart",  aspectRatio: "1392/1488", span: true },
    ],
  },
  { id: "bt-research-heading", type: "heading", content: "The Research" },
  { id: "bt-audit-label", type: "subheading", content: "Competitive Audit" },
  { id: "bt-audit-desc", type: "paragraph", content: "After evaluating the following competitors, David was able to take the strengths and weaknesses of each platform and use them to Battery Trader's advantage." },
  { id: "bt-audit-table", type: "table", label: "Competitive Audit", headers: ["Competitor", "Strengths", "Weakness", "Pricing", "Support"], rows: [
    ["PCI",              "Faster performance due to new technology",              "Product hasn't been on the market as long as others", "$2,100/mo", "Support has always been key to PCI's success"],
    ["Tesla",            "Seamless integration experience, great UI",             "Not much interaction with customers",                  "$2,800/mo", "Great documentation, little to no live support"],
    ["New Era 360",      "Uses supporting 3rd-party software integration",        "UX hard to navigate through",                         "$2,000/mo", "Not much support after onboarding"],
    ["Energy One",       "Great UI design and usability",                         "Data retrieval is laggy and really slow",              "$1,800/mo", "Not much support after onboarding"],
    ["Ascend Analytics", "Makes great use of all roles involved in workflow",     "UI is really outdated and UX is not intuitive",        "$1,800/mo", "Only provides support tickets"],
  ]},
  { id: "bt-pain-intro", type: "subheading", content: "The User Pain Points" },
  { id: "bt-pain-intro-desc", type: "paragraph", content: "After discovery interviews with a total of 9 participants, including day-ahead traders, real-time traders, analysts, and administrators, the team identified four recurring pain points." },
  { id: "bt-pain1-label", type: "subheading", content: "Making Complexity Manageable" },
  { id: "bt-pain1", type: "paragraph", content: "Tackling the complexities of energy markets head-on, the platform offers intuitive tools to cut through the intricacies, making it easier for users to optimize bids and enhance profits. Multi-market navigation becomes straightforward strategy, ensuring seamless decision-making." },
  { id: "bt-pain2-label", type: "subheading", content: "Keeping Pace with the Market" },
  { id: "bt-pain2", type: "paragraph", content: "In energy trading, time is of the essence. Every moment spent waiting for data to refresh or an interface to respond is a missed opportunity. Traders need software that keeps up with the breakneck speed of real-time markets, where updates are instantaneous and performance hiccups are a thing of the past." },
  { id: "bt-pain3-label", type: "subheading", content: "Empowering Decisions with Smarter Tools" },
  { id: "bt-pain3", type: "paragraph", content: "The right decision hinges on having the right information at the right time, presented in a way that's easy to understand and act upon. Many platforms fall short, offering either oversimplified tools or complex systems that require a manual to decipher. Traders are looking for advanced, yet accessible analytics that sharpen their edge." },
  { id: "bt-pain4-label", type: "subheading", content: "Simplifying the Routine with Automation" },
  { id: "bt-pain4", type: "paragraph", content: "Between submitting bids and staying alert to market shifts, traders have their hands full. They dream of a platform that takes care of the menial tasks, like a trusted assistant that knows exactly when to alert them to opportunities or submit bids on their behalf, freeing them to focus on the bigger picture." },
  { id: "bt-personas-heading", type: "heading", content: "User Personas" },
  { id: "bt-alex", type: "persona",
    name: "Alex Johnson",
    meta: "Day-Ahead Energy Trader · Age 35 · New York, NY",
    quote: "I'm constantly battling with software that complicates rather than simplifies market analysis, making it tough to quickly adapt my trading strategies.",
    goals: [
      "Streamline complex market analysis with intuitive software",
      "Rely on accurate forecasting tools",
      "Automate routine tasks like bid submissions",
    ],
    frustrations: [
      "Clunky and complex interfaces",
      "Unreliable forecasting tools",
      "Time-consuming manual bid processes",
    ],
  },
  { id: "bt-samantha", type: "persona",
    name: "Samantha Lee",
    meta: "Real-Time Energy Trader · Age 29 · Houston, TX",
    quote: "The lag and clumsiness of current trading platforms hinder my ability to make swift, informed decisions in a market where every second counts.",
    goals: [
      "Instantly analyze and act on real-time data",
      "Access critical features quickly",
      "Reduce decision-making delays",
    ],
    frustrations: [
      "Slow updates and data lags",
      "Clumsy outdated UI",
      "Inefficient real-time analysis tools",
    ],
  },
  { id: "bt-validation-heading", type: "heading", content: "Design Validation" },
  { id: "bt-lofi-label", type: "subheading", content: "Low-Fidelity Prototype" },
  { id: "bt-lofi-desc", type: "paragraph", content: "After receiving discovery-phase data from the project team and users, David moved into low-fidelity prototypes for validation and feedback." },
  { id: "bt-lofi-grid", type: "image-grid", images: [
    { src: "/images/battery-trader/lo-fi.png",  alt: "Battery Trader lo-fidelity prototype",  aspectRatio: "1416/675" },
    { src: "/images/battery-trader/mid-fi.png", alt: "Battery Trader mid-fidelity prototype", aspectRatio: "1416/675" },
  ]},
  { id: "bt-usability-label", type: "subheading", content: "Usability Study: Findings" },
  { id: "bt-usability-desc", type: "paragraph", content: "When lo-mid fidelity was finished, the team took it internally and externally to get feedback from users for any missed opportunities or design pain points." },
  { id: "bt-usability-grid", type: "image-grid", images: [
    { src: "/images/battery-trader/user-video-3.png", alt: "Usability study session 1", aspectRatio: "1416/797" },
    { src: "/images/battery-trader/user-video-4.png", alt: "Usability study session 2", aspectRatio: "1416/794" },
  ]},
  { id: "bt-findings", type: "list", label: "", items: [
    "Tailored dashboards: users loved how easy it was to make the dashboard their own; quick tweaks kept their favorite tools at their fingertips.",
    "Speedy updates: the real-time data ticked just right, matching the market's pulse, a game-changer for split-second decisions.",
    "Clear insights: analytics and visuals struck a balance, rich in insight but clear and digestible.",
    "Smooth sailing: the UI's smooth, intuitive feel got two thumbs up; even complex features felt accessible.",
  ]},
  { id: "bt-render", type: "image", src: "/images/battery-trader/render.png", alt: "Battery Trader product render" },
  { id: "bt-hifi-heading", type: "heading", content: "Iterating Hi-Fidelity Designs" },
  { id: "bt-hifi-desc", type: "paragraph", content: "Based on the feedback from the usability study, David moved into hi-fi designs that speak directly to users' needs, fine-tuning everything from snappy real-time updates to sleek analytics, making sure each aspect is as user-friendly and engaging as possible." },
  { id: "bt-hifi-all", type: "image", src: "/images/battery-trader/hi-fi-all.png", alt: "All Battery Trader high-fidelity screens" },
  { id: "bt-hifi-grid", type: "image-grid", images: [
    { src: "/images/battery-trader/hi-1.png", alt: "Battery Trader screen 1", aspectRatio: "928/1326" },
    { src: "/images/battery-trader/hi-2.png", alt: "Battery Trader screen 2", aspectRatio: "928/1326" },
    { src: "/images/battery-trader/hi-3.png", alt: "Battery Trader screen 3", aspectRatio: "928/1326" },
  ]},
  { id: "bt-forward-heading", type: "heading", content: "Going Forward" },
  { id: "bt-impact-label", type: "subheading", content: "Impact" },
  { id: "bt-impact", type: "paragraph", content: "The enhanced visuals in the UI were a game-changer during testing for traders and analysts, significantly improving their ability to make well-informed bids. The visualizations distill complex data into clear, actionable insights, enabling users to quickly identify and act on market opportunities." },
  { id: "bt-learned-label", type: "subheading", content: "What David Learned" },
  { id: "bt-learned", type: "paragraph", content: "Users crave control within a unified, efficient space. Emphasizing customization and streamlined workflows significantly boosted user efficiency and satisfaction. Giving users the ability to tailor their experience directly impacts a tool's effectiveness and their overall contentment." },
  { id: "bt-next-label", type: "subheading", content: "Next Steps" },
  { id: "bt-next", type: "list", label: "", items: [
    "Develop a tablet app, optimized for touch controls and usable on a smaller screen.",
    "Conduct usability testing with real users post-development to refine ease of use and effectiveness.",
  ]},
  { id: "bt-outro", type: "outro", content: "Want to know more {{about}} David Rivas? You can also see {{his skills}} or check out {{Sole Lucky}}.", links: [
    { label: "about", query: "/about" },
    { label: "his skills", query: "/skills" },
    { label: "Sole Lucky", query: "/projects/sole-lucky" },
  ]},
];
