import type { Section } from "@/components/features/section-types";

export const DESIGN_SKILLS_SECTIONS: Section[] = [
  { id: "ds-title", type: "heading", content: "Design Skills & Guardrails System" },
  { id: "ds-hero", type: "image", src: "/images/design-skills/hero.png", alt: "Design Skills & Guardrails System hero" },
  { id: "ds-meta", type: "meta", lines: [
    { label: "Client",   value: "Dais Co." },
    { label: "Timeline", value: "Nov 2025–Mar 2026" },
    { label: "Platform", value: "Design System" },
    { label: "Role",     value: "Lead Product Design, AI Orchestrator" },
    { label: "Tools",    value: "Figma, Claude AI & Code, Tailwind, ShadCN, Gitlab" },
  ]},
  { id: "ds-intro-label", type: "subheading", content: "Introduction" },
  { id: "ds-intro", type: "paragraph", content: "Dais had adopted shadcn's default component library along with a Figma-connected MCP integration for Claude Code. The MCP read component structure and existing styles reliably at the atom and molecule level. The failure showed up one layer up: at the organism, template, and page level, where shadcn's default tokens — structural placeholders rather than semantic definitions — gave Claude Code nothing to resolve against. It started inferring semantics from visual proximity instead of an explicit mapping." },
  { id: "ds-goal-label", type: "subheading", content: "The Goal" },
  { id: "ds-goal", type: "paragraph", content: "Build a token and skill file system that gives Claude Code, and the engineers working alongside it, unambiguous semantic ground truth across product, marketing, and PoC surfaces — without requiring a human to manually review every AI-generated output to catch drift." },
  { id: "ds-challenge-label", type: "subheading", content: "The Challenge" },
  { id: "ds-challenge", type: "paragraph", content: "This is a coordination problem that gets worse, not better, with AI-assisted development. Traditional design drift happens slowly, one engineer's judgment call at a time. AI-generated drift happens instantly and at volume — a model without a defined system will confidently invent one, differently, every time it's asked. As the sole product designer covering three surfaces at once, the fix had to be structural rather than supervisory." },
  { id: "ds-process-label", type: "subheading", content: "The Process" },
  { id: "ds-process", type: "paragraph", content: "Four stages: research how other teams were solving the same class of problem, redesign the token architecture itself rather than patch shadcn's defaults, build and validate one skill file per surface in a sandboxed environment, then document and roll out." },

  { id: "ds-research-heading", type: "heading", content: "The Research" },
  { id: "ds-research1", type: "paragraph", content: "Before rebuilding the token system, David studied how other AI-forward companies — particularly ones using AI to iterate on design in code or run automated A/B testing — structured their design tokens in shipped, publicly inspectable code. Not to copy their systems, but to understand what a token architecture looks like once a team has had to make it work under AI-driven iteration rather than only human designers hand-authoring components." },
  { id: "ds-research2", type: "paragraph", content: "The pattern across nearly all of them: they'd gone a step further than shadcn's defaults by defining real component-level semantics — purpose-mapped tokens rather than raw structural placeholders. But almost none had simplified that layer. Most still defined state and style semantics per component rather than sharing them across components that played the same functional role. That gap — correct in principle but not simplified in practice — is what shaped the decision to build shared, universal component semantics into the Product UI skill file." },
  { id: "ds-gap-diagram", type: "callout-stack",
    items: [
      { label: "Industry Pattern", body: "Component-level semantics defined",           theme: "neutral"  },
      { label: "The Gap",          body: "State logic duplicated per component",         theme: "orange"   },
      { label: "The Fix",          body: "One shared semantic layer",                    theme: "emerald"  },
    ],
    footer: "Inherited across every related component",
  },

  { id: "ds-approach-heading", type: "heading", content: "The Approach" },
  { id: "ds-approach", type: "paragraph", content: "The fix was rebuilding the semantic layer using the W3C Design Tokens format. Every semantic token carries an explicit alias reference back to a specific primitive variable, so a new template being generated for the first time had the same semantic ground truth as a component that had already been built." },
  { id: "ds-token-hierarchy", type: "callout-stack",
    items: [
      { label: "Component Tokens", body: "What a component references",   theme: "teal-mid"   },
      { label: "Semantic Tokens",  body: "Purpose, mapped explicitly",    theme: "teal-light" },
      { label: "Primitive Tokens", body: "The literal source value",      theme: "teal-dark"  },
    ],
  },
  { id: "ds-system-heading", type: "heading", content: "The System" },
  { id: "ds-system-desc", type: "paragraph", content: "Three skill files — one per surface — each with its own token constraints and component state logic, built on the shared primitive and semantic foundation." },
  { id: "ds-surfaces-grid", type: "image-grid", columns: 3, images: [
    { src: "/images/design-skills/poc-ui.png",       alt: "PoC Skills",     columnLabel: "PoC Skills",          caption: { title: "PoC skills",          body: "Constrained tokens, simplified guardrails", theme: "neutral"   } },
    { src: "/images/design-skills/product-ui.png",   alt: "Product UI",     columnLabel: "Product UI Skills",   caption: { title: "Product UI skills",   body: "Shared component state logic",              theme: "teal"      } },
    { src: "/images/design-skills/marketing-ui.png", alt: "Marketing UI",   columnLabel: "Marketing UI Skills", caption: { title: "Marketing UI skills", body: "Shared component state logic",              theme: "teal-dark" } },
  ]},
  { id: "ds-token-arch-card", type: "token-arch" },
  { id: "ds-poc", type: "split", heading: "PoC Skill File", content: "Stakeholders in demos would fixate on visual polish rather than workflow logic. A reduced grayscale palette, single radius, and simplified state model structurally prevented high-fidelity output — so the constraint was a ceiling, not a suggestion.", src: "/images/design-skills/design-system-poc.png", alt: "Design System PoC" },
  { id: "ds-product", type: "split", heading: "Product UI Skill File", content: "Shared component state logic. The semantic layer was restructured so state changes are defined once and inherited across components sharing a functional role, closing the drift gap the research surfaced in other companies' systems.", src: "/images/design-skills/design-system-product.png", alt: "Design System Product" },
  { id: "ds-marketing", type: "split", heading: "Marketing UI Skill File", content: "Shared component state logic, with more expressive range — larger type, broader color, gradients — without losing the component logic connecting it to product. Guardrails direct the model toward marketing-appropriate token choices rather than constraining toward simplicity.", src: "/images/design-skills/design-system-marketing.png", alt: "Design System Marketing" },

  { id: "ds-validation-heading", type: "heading", content: "Validation Methodology" },
  { id: "ds-validation", type: "paragraph", content: "No automated lint or CI check enforced this yet, so the validation loop was manual but repeatable: run a generation pass, inspect resolved output against the token structure, log mismaps, adjust, rerun. This cycled until output converged to roughly 99% correct token resolution." },
  { id: "ds-pipeline", type: "badge-flow",
    steps: ["Sandbox build", "Generate", "Compare to Figma MCP", "Log mismaps", "Adjust", "Rerun"],
    result: "99% resolved",
  },

  { id: "ds-forward-heading", type: "heading", content: "Going Forward" },
  { id: "ds-impact-label", type: "subheading", content: "Impact" },
  { id: "ds-impact", type: "paragraph", content: "The token restructuring and validation loop were built and validated solo, in a sandboxed repo branch, until output converged to near-total accuracy across the atom, molecule, and previously-undefined organism/template/page levels." },
  { id: "ds-learned-label", type: "subheading", content: "What David Learned" },
  { id: "ds-learned", type: "paragraph", content: "The next phase was bringing engineers directly into the testing loop, validating against real production usage before company-wide rollout. That phase hadn't started before a round of layoffs — which included several of the engineers who would have been part of that testing — ended the initiative." },
  { id: "ds-next-label", type: "subheading", content: "Next Steps" },
  { id: "ds-next", type: "paragraph", content: "Building and validating a system solo gave David real confidence that it worked the way it was designed to. It didn't tell him how it survives contact with people who didn't build it. Not every system gets to finish its intended validation cycle, and knowing precisely what that next phase should have been is itself part of the work." },
  { id: "ds-outro", type: "outro", content: "Want to know more {{about}} David Rivas? You can also check out {{Battery Trader}} or {{Sole Lucky}}.", links: [
    { label: "about", query: "/about" },
    { label: "Battery Trader", query: "/projects/battery-trader" },
    { label: "Sole Lucky", query: "/projects/sole-lucky" },
  ]},
];
