import type { Section } from "@/components/features/section-types";

export const HITHE_SECTIONS: Section[] = [
  { id: "hi-title", type: "heading", content: "Hithe" },
  { id: "hi-hero1", type: "image", src: "/images/hithe/hero-1.png", alt: "Hithe hero" },
  { id: "hi-meta", type: "meta", lines: [
    { label: "Client",   value: "Dais Co." },
    { label: "Timeline", value: "Apr–Jun 2026" },
    { label: "Platform", value: "Web" },
    { label: "Role",     value: "Lead Product Designer" },
    { label: "Tools",    value: "Figma, Claude Code" },
  ]},
  { id: "hi-intro-label", type: "subheading", content: "Introduction" },
  { id: "hi-intro", type: "paragraph", content: "Hithe is an LLM gateway and proxy. Every application that needs to call a model routes through Hithe instead of hitting the provider directly, and in exchange, Hithe adds metering, governance, auditability, and compliance controls on top of that traffic. It isn't a workflow builder — it's infrastructure that sits underneath wherever workflows eventually make their model calls, positioned to eventually replace Horizon, Dais's node-based agentic workflow product." },
  { id: "hi-hero2", type: "image", src: "/images/hithe/hero-2.png", alt: "Hithe product overview", height: 183 },
  { id: "hi-goal-label", type: "subheading", content: "The Goal" },
  { id: "hi-goal", type: "paragraph", content: "Design a gateway interface that a compliance officer — not just an engineer — can trust at a glance, one where the parts of the product carrying legal and safety weight are visually and structurally distinct from routine configuration." },
  { id: "hi-challenge-label", type: "subheading", content: "The Challenge" },
  { id: "hi-challenge", type: "paragraph", content: "A metering and governance product succeeds or fails on a specific kind of trust: the customer isn't just asking \"does this work,\" they're asking \"can I prove to my own auditors that this worked, every time, for every request.\" That's a harder design problem than most SaaS products solve, because the interface itself is part of the compliance story, not just a way to configure the product." },
  { id: "hi-discovery-heading", type: "heading", content: "Discovery Phase" },
  { id: "hi-structure-label", type: "subheading", content: "Building the structure" },
  { id: "hi-structure", type: "paragraph", content: "David reconstructed the product screen by screen from the live product, following an initial discovery conversation with Dais's VP of Engineering about Hithe's direction. The audit surfaced structural issues invisible from any single screen — duplicate settings, conflicting billing surfaces, and an approval flow with no second reviewer to use it." },
  { id: "hi-ia", type: "image", src: "/images/hithe/ia-structure.png", alt: "Hithe IA structure" },
  { id: "hi-research-heading", type: "heading", content: "The Research" },
  { id: "hi-audit-label", type: "subheading", content: "Competitive Audit" },
  { id: "hi-audit-desc", type: "paragraph", content: "The LLM gateway market splits cleanly along one axis: self-hosted, developer-first tools built for routing flexibility, versus managed, compliance-first platforms built for regulated enterprises. Hithe sits — or needs to sit — firmly in the second category." },
  { id: "hi-audit-table", type: "table", label: "Competitive Audit", headers: ["Competitor", "Strengths", "Weakness", "Compliance"], rows: [
    ["Portkey",      "Deep observability, 50+ pre-built guardrails, PII redaction and jailbreak detection",          "Adds 20–40ms latency; BAA process alone can take 2–3 weeks",                       "SOC 2, HIPAA, GDPR, ISO 27001"],
    ["LiteLLM",     "Broad provider coverage (100+), free to self-host, strong for fast iteration",                 "No built-in guardrails; Python GIL bottleneck above ~500 RPS",                     "No formal compliance certifications"],
    ["TrueFoundry", "Full VPC or air-gapped deployment, governs model traffic and agent tool access via MCP Gateway","Kubernetes-native, heavier operational lift",                                       "SOC 2 Type 2, HIPAA, GDPR; full data sovereignty"],
    ["Kong AI",     "Strong plugin ecosystem, natural fit for teams already on Kong for API management",             "Steep learning curve; heaviest to stand up",                                       "Enterprise-grade access control via Kong infrastructure"],
  ]},
  { id: "hi-takeaway-label", type: "subheading", content: "Takeaway" },
  { id: "hi-takeaway", type: "paragraph", content: "Hithe's positioning: the products winning in regulated-industry deals aren't winning on routing features — LiteLLM already does that for free. They're winning on making compliance and audit posture visible and provable inside the product itself. That's the gap Hithe's interface needs to close, and none of these four fully solve it at the interface level either." },
  { id: "hi-pain-label", type: "subheading", content: "The Pain Points" },
  { id: "hi-pain", type: "list", label: "", items: [
    "Proving it, not just doing it — regulated customers need to demonstrate the gateway enforced policy correctly to an auditor who wasn't in the room. An interface that can't visually distinguish a routine event from a compliance-relevant one makes that demonstration harder than it needs to be.",
    "Trusting an ambiguous status — when a system status is unclear, a compliance-minded user's default assumption is the worst case, not the best one. An unexplained \"Retrying\" indicator reads as something to worry about.",
    "Telling shipped from roadmap — a customer evaluating whether to trust this gateway with PHI traffic needs a confident answer to \"what does this actually do today.\"",
  ]},
  { id: "hi-personas-heading", type: "heading", content: "User Personas" },
  { id: "hi-priya", type: "persona",
    name: "Priya Nadarajah",
    meta: "Compliance and Security Lead · Age 41 · Minneapolis, MN",
    quote: "I don't need the gateway to be clever. I need to be able to open this dashboard during an audit and answer every question the auditor asks without opening a second tool.",
    goals: [
      "Confirm PHI-tier traffic routes only to BAA-covered providers",
      "Produce audit evidence without engineering's help",
      "Distinguish routine activity from compliance-relevant events at a glance",
    ],
    frustrations: [
      "Compliance events and general system logs look identical",
      "No visual signal for which flows carry legal weight",
    ],
  },
  { id: "hi-marcus", type: "persona",
    name: "Marcus Webb",
    meta: "Platform Engineering Lead · Age 34 · Austin, TX",
    quote: "I'm the one who gets paged when something looks wrong. I need the interface to tell me immediately whether 'Retrying' is my problem or nobody's problem.",
    goals: [
      "Resolve ambiguous system status without opening a support ticket",
      "Understand at a glance whether a billing figure is what his team owes upstream or what they're charging downstream",
    ],
    frustrations: [
      "The Retrying badge gives no indication of severity or next action",
      "Subscriptions and Plan Usage use nearly identical language for opposite billing directions",
    ],
  },
  { id: "hi-render", type: "image", src: "/images/hithe/render.png", alt: "Hithe product render" },
  { id: "hi-hifi-heading", type: "heading", content: "Hi-Fidelity Designs" },
  { id: "hi-hifi-state", type: "subheading", content: "Current State" },
  { id: "hi-hifi-desc", type: "paragraph", content: "These are the current, in-progress high-fidelity mockups for the proposed direction. They reflect design decisions made from the audit findings alone — they have not been through usability testing or stakeholder feedback sessions, since that phase hadn't started before David's involvement with the product ended. Treat these as a working direction, not a validated one." },
  { id: "hi-hifi-all", type: "image", src: "/images/hithe/hi-fi-all.png", alt: "Hithe hi-fidelity all screens" },
  { id: "hi-hifi-grid", type: "image-grid", images: [
    { src: "/images/hithe/hi-1.png", alt: "Hithe screen 1", aspectRatio: "928/1326" },
    { src: "/images/hithe/hi-2.png", alt: "Hithe screen 2", aspectRatio: "928/1326" },
    { src: "/images/hithe/hi-3.png", alt: "Hithe screen 3", aspectRatio: "928/1326" },
  ]},
  { id: "hi-forward-heading", type: "heading", content: "Going Forward" },
  { id: "hi-impact-label", type: "subheading", content: "Impact" },
  { id: "hi-impact", type: "paragraph", content: "The audit surfaced concrete, specific risks in a product built for a compliance-sensitive audience — most notably that its two safety-critical flows were visually indistinguishable from routine settings pages. That's a finding with real product implications regardless of who acts on it next." },
  { id: "hi-learned-label", type: "subheading", content: "What David Learned" },
  { id: "hi-learned", type: "paragraph", content: "The next phase would have been validating the proposed direction with the people who actually carry the compliance and legal risk — likely legal or compliance stakeholders alongside engineering — before any of it touched a real interface. That validation never happened. Ownership of Hithe was still in transition when a round of layoffs, including David's own, ended his involvement with the product." },
  { id: "hi-next-label", type: "subheading", content: "Next Steps" },
  { id: "hi-next", type: "paragraph", content: "The next phase would have been bringing the proposed direction into validation with compliance and legal stakeholders, not just engineering, before any of it shipped. Knowing precisely what that phase should have been — and why it matters for this specific product category — is itself part of the work." },
  { id: "hi-outro", type: "outro", content: "Want to know more {{about}} David Rivas? You can also check out {{Design Skills & Guardrails}} or {{Battery Trader}}.", links: [
    { label: "about", query: "/about" },
    { label: "Design Skills & Guardrails", query: "/projects/design-skills-guardrails" },
    { label: "Battery Trader", query: "/projects/battery-trader" },
  ]},
];
