import type { Section } from "@/components/features/section-types";

export const SOLE_LUCKY_SECTIONS: Section[] = [
  { id: "sl-title", type: "heading", content: "Sole Lucky" },
  { id: "sl-hero1", type: "image", src: "/images/sole-lucky/hero-1.png", alt: "Sole Lucky hero" },
  { id: "sl-meta", type: "meta", lines: [
    { label: "Client",   value: "Funk Products" },
    { label: "Timeline", value: "Jan–Mar 2023" },
    { label: "Platform", value: "iOS" },
    { label: "Role",     value: "UX Research, Product Design, Brand & UI System" },
    { label: "Tools",    value: "Figma, Adobe CC, Google Products" },
  ]},
  { id: "sl-intro-label", type: "subheading", content: "Introduction" },
  { id: "sl-intro", type: "paragraph", content: "Sole Lucky reimagines how people get access to limited sneaker releases. Instead of competing against bots and resellers on the secondary market, users enter raffles for a chance to buy at retail price, and a points system rewards repeat participation with better odds over time." },
  { id: "sl-hero2", type: "image", src: "/images/sole-lucky/hero-2.png", alt: "Sole Lucky app overview" },
  { id: "sl-goal-label", type: "subheading", content: "The Goal" },
  { id: "sl-goal", type: "paragraph", content: "Design an app where users feel like they're getting a fair shot at exclusive releases, not just another chance to lose to automated buying." },
  { id: "sl-challenge-label", type: "subheading", content: "The Challenge" },
  { id: "sl-challenge", type: "paragraph", content: "Sneaker raffles have a trust problem. Most platforms don't explain how winners are chosen, bots dominate high-demand drops, and resale prices push casual fans out of the market entirely. The design challenge was building a raffle experience transparent enough that users could trust the odds, wrapped in a UI clean enough to compete with retail-grade apps." },
  { id: "sl-process-label", type: "subheading", content: "The Process" },
  { id: "sl-process", type: "paragraph", content: "David started with a quantitative survey to understand where existing raffle and resale apps were failing users, then moved into a competitive audit of the sneaker resale market. From there he built the brand, sketched early concepts, and worked through wireframes, prototypes, and a round of usability testing before refining the final UI." },
  { id: "sl-research-heading", type: "heading", content: "The Research" },
  { id: "sl-audit-label", type: "subheading", content: "Competitive Audit & Survey" },
  { id: "sl-audit", type: "paragraph", content: "After evaluating StockX, GOAT, eBay, and Foot Locker, David pulled the strengths and weaknesses of each into the research and used them to Sole Lucky's advantage. David also ran a quantitative survey with 20 participants to understand pain points with existing sneaker raffle and resale apps, covering screener questions, pain points, and open feedback." },
  { id: "sl-pain-points", type: "list", label: "", items: [
    "Price: Resale markup was the single biggest frustration. Users felt priced out of releases they should have had a fair shot at.",
    "Bots: Automated entries were seen as rigging raffles against real buyers, eroding trust in the fairness of the process.",
    "Poor UX: No Face ID, no saved payment info, and apps signing users out mid-raffle were recurring complaints across the platforms tested.",
  ]},
  { id: "sl-personas-heading", type: "subheading", content: "User Personas" },
  { id: "sl-ryan", type: "persona",
    name: "Ryan McClure",
    meta: "Sneaker Enthusiast · Age 23 · Oklahoma City, OK",
    quote: "I don't need the hookup, I just want a fair shot at retail price.",
    goals: [
      "Access releases without resale markup",
      "Trust the raffle is actually fair",
      "Fast low-friction entry flow",
    ],
    frustrations: [
      "Bots dominating high-demand drops",
      "Resale prices",
      "Apps logging out mid-raffle",
    ],
  },
  { id: "sl-carlos", type: "persona",
    name: "Carlos",
    meta: "Family Shopper · Age 42 · Bixby, OK",
    quote: "I want to see what I need, get it, and get out.",
    goals: [
      "Multiple payment options",
      "More categories (women's, kids')",
      "Instant release alerts",
    ],
    frustrations: [
      "Slow laggy apps",
      "Feeling bots rigged the outcome",
    ],
  },
  { id: "sl-validation-heading", type: "heading", content: "Design Validation" },
  { id: "sl-sketches-label", type: "subheading", content: "Sketches → Wireframes → Low-Fidelity Prototype" },
  { id: "sl-sketches-desc", type: "paragraph", content: "Early sketches kept the design anchored to what stakeholders cared about most: a fast, low-friction entry flow. Wireframes translated that into screen-level decisions, and the low-fidelity prototype focused on making the raffle entry and points system feel effortless before testing it with real users." },
  { id: "sl-design-validation-grid", type: "split-stack",
    left: [
      { src: "/images/sole-lucky/sketches.png", alt: "Early sketches" },
      { src: "/images/sole-lucky/lo-fi.png",    alt: "Low-fidelity prototype" },
    ],
    right: { src: "/images/sole-lucky/mid-fi.png", alt: "Mid-fidelity wireframes" },
  },
  { id: "sl-usability-label", type: "subheading", content: "Usability Study" },
  { id: "sl-usability", type: "list", label: "", items: [
    "Users wanted Face ID for login and purchases.",
    "Apple/Google Pay alone wasn't enough; users expected multiple card options.",
    "Users wanted to browse before being forced into signup.",
    "The homepage needed to surface more than men's releases, including women's and kids'.",
  ]},
  { id: "sl-brand-heading", type: "heading", content: "Brand & UI System" },
  { id: "sl-typography-label", type: "subheading", content: "Typography" },
  { id: "sl-turret", type: "paragraph", content: "Turret Road: Display and headline use only (logo, section titles, hero moments). A condensed sans with a technical, slightly industrial character; works well at large sizes but gets harder to read in long-form text, so it stays out of body copy entirely." },
  { id: "sl-jetbrains", type: "paragraph", content: "JetBrains Mono: UI body, labels, and all functional/data text. Sole Lucky is full of numeric, functional data: prices, sizes, points, entry counts, deadlines. A mono face makes that information feel deliberate and legible rather than decorative, and reinforces an agile product feel over lifestyle-brand polish." },
  { id: "sl-brand-images", type: "image-grid", images: [
    { src: "/images/sole-lucky/brand-1.png", alt: "Sole Lucky brand identity 1" },
    { src: "/images/sole-lucky/brand-2.png", alt: "Sole Lucky brand identity 2" },
    { src: "/images/sole-lucky/brand-3.png", alt: "Sole Lucky brand identity 3" },
  ]},
  { id: "sl-type-scale", type: "table", label: "Type Scale", headers: ["Style", "Font", "Size", "Weight", "Leading", "Usage"], rows: [
    ["Display",    "Turret Road",    "32px", "700 Bold",    "38px", "Logo, hero moments"],
    ["Heading 1",  "Turret Road",    "24px", "700 Bold",    "29px", "Section titles"],
    ["Body Large", "JetBrains Mono", "18px", "400 Regular", "27px", "Intro copy"],
    ["Body",       "JetBrains Mono", "16px", "400 Regular", "24px", "UI body text"],
    ["Label",      "JetBrains Mono", "14px", "400 Regular", "20px", "Metadata, tags"],
    ["Caption",    "JetBrains Mono", "12px", "400 Regular", "18px", "Timestamps, footnotes"],
  ]},
  { id: "sl-color-table", type: "table", label: "Color Palette", headers: ["Token", "Hex / Value", "Usage"], rows: [
    ["Brand Black",  "#0A0A0A",                "Page background"],
    ["Off-white",    "#F5F4F0",                "Primary text"],
    ["Lucky Orange", "#FF6B2B",                "CTAs, primary accent"],
    ["Point Gold",   "#F5B300",                "Points, rewards, badges"],
    ["Success",      "#22C55E",                "Win/confirm states"],
    ["Error",        "#EF4444",                "Error states, destructive"],
    ["Surface",      "#1A1A1A",                "Card backgrounds"],
    ["Border",       "rgba(255,255,255,0.12)", "Dividers, outlines"],
  ]},
  { id: "sl-states-table", type: "table", label: "Functional States", headers: ["Component", "Default", "Hover", "Pressed", "Disabled", "Focus"], rows: [
    ["Primary Button",  "Orange fill, white label",  "Lighten 10%",        "Scale 0.97",  "30% opacity, no events", "2px ring, 2px offset"],
    ["Secondary Button","Outline stroke",             "BG fill 8%",         "Scale 0.97",  "30% opacity",            "Ring primary"],
    ["Input",           "Border 12% opacity",         "Border 24% opacity", "N/A",         "Muted background",       "Ring primary color"],
    ["Raffle Card",     "Surface background",         "Surface + 8% lift",  "N/A",         "50% opacity",            "Ring offset 2px"],
    ["Tab / Nav Item",  "No underline",               "Underline subtle",   "Bold weight", "N/A",                    "Outline 2px"],
  ]},
  { id: "sl-render", type: "image", src: "/images/sole-lucky/render.png", alt: "Sole Lucky product render" },
  { id: "sl-hifi-heading", type: "heading", content: "Hi-Fidelity" },
  { id: "sl-hifi-desc", type: "paragraph", content: "The final designs added expanded homepage categories (men's, women's, kids') and built in the points-based reward system that gives users better raffle odds the more they participate." },
  { id: "sl-hifi-all", type: "image", src: "/images/sole-lucky/hi-fi-all.png", alt: "All high-fidelity screens" },
  { id: "sl-hifi-grid", type: "image-grid", columns: 2, images: [
    { src: "/images/sole-lucky/login.png",    alt: "Login screen" },
    { src: "/images/sole-lucky/points.png",   alt: "Points screen" },
    { src: "/images/sole-lucky/browse.png",   alt: "Browse screen" },
    { src: "/images/sole-lucky/checkout.png", alt: "Checkout screen" },
  ]},
  { id: "sl-forward-heading", type: "heading", content: "Going Forward" },
  { id: "sl-impact-label", type: "subheading", content: "Impact" },
  { id: "sl-impact", type: "paragraph", content: "Sole Lucky gives users like Ryan a fair, bot-resistant shot at retail-priced releases instead of competing against automated buying, and gives users like Carlos a faster, family-friendly shopping experience with the payment flexibility and category range he needed. The points system rewards continued participation with better odds over time, rather than treating every entry as an equal coin flip regardless of history." },
  { id: "sl-learned-label", type: "subheading", content: "What David Learned" },
  { id: "sl-learned", type: "paragraph", content: "Designing for a points-based access system meant every product decision had to account for perceived fairness, not just usability. Ryan and Carlos needed different things from the app, but both needed to trust that the raffle mechanic itself wasn't rigged. That's a harder design problem than clean UI alone solves." },
  { id: "sl-next-label", type: "subheading", content: "Next Steps" },
  { id: "sl-next", type: "list", label: "", items: [
    "Build a responsive companion site for desktop users.",
    "Run a usability round focused specifically on whether the points system feels fair and transparent to users.",
    "Revisit the competitive audit periodically, since resale and raffle apps change their fee and access models often.",
  ]},
  { id: "sl-outro", type: "outro", content: "Want to know more {{about}} David Rivas? You can also see {{his skills}} or check out {{Battery Trader}}.", links: [
    { label: "about", query: "/about" },
    { label: "his skills", query: "/skills" },
    { label: "Battery Trader", query: "/projects/battery-trader" },
  ]},
];
